apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketNotification
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1beta1/bucketnotification
  labels:
    testing.upbound.io/example-name: bucket_notification
  name: bucket-notification
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: bucket
    region: us-west-1
    topic:
    - events:
      - s3:ObjectCreated:*
      filterSuffix: .log
      topicArn: ${aws_sns_topic.topic.arn}

---

apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: ${Rand.RFC1123Subdomain}
    meta.upbound.io/example-id: s3/v1beta1/bucketnotification
  labels:
    testing.upbound.io/example-name: bucket
  name: bucket
spec:
  forProvider:
    region: us-west-1

---

