apiVersion: ec2.aws.upbound.io/v1beta1
kind: FlowLog
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/flowlog
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    iamRoleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    logDestinationSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    region: us-west-1
    trafficType: ALL
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/flowlog
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
              "Service": "vpc-flow-logs.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }

---

