apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPCEndpointConnectionNotification
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/vpcendpointconnectionnotification
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    connectionEvents:
    - Accept
    - Reject
    connectionNotificationArn: ${aws_sns_topic.topic.arn}
    region: us-west-1
    vpcEndpointServiceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPCEndpointService
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/vpcendpointconnectionnotification
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    acceptanceRequired: false
    networkLoadBalancerArns:
    - ${aws_lb.test.arn}
    region: us-west-1

---

