/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

// Package apis contains Kubernetes API for the provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1beta1 "github.com/upbound/provider-aws/apis/autoscaling/v1beta1"
	v1beta1deploy "github.com/upbound/provider-aws/apis/deploy/v1beta1"
	v1beta1ec2 "github.com/upbound/provider-aws/apis/ec2/v1beta1"
	v1beta1iam "github.com/upbound/provider-aws/apis/iam/v1beta1"
	v1beta1kms "github.com/upbound/provider-aws/apis/kms/v1beta1"
	v1beta1rds "github.com/upbound/provider-aws/apis/rds/v1beta1"
	v1beta1resourcegroups "github.com/upbound/provider-aws/apis/resourcegroups/v1beta1"
	v1beta1s3 "github.com/upbound/provider-aws/apis/s3/v1beta1"
	v1beta1s3control "github.com/upbound/provider-aws/apis/s3control/v1beta1"
	v1alpha1 "github.com/upbound/provider-aws/apis/v1alpha1"
	v1beta1apis "github.com/upbound/provider-aws/apis/v1beta1"
	v1beta1vpc "github.com/upbound/provider-aws/apis/vpc/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1beta1.SchemeBuilder.AddToScheme,
		v1beta1deploy.SchemeBuilder.AddToScheme,
		v1beta1ec2.SchemeBuilder.AddToScheme,
		v1beta1iam.SchemeBuilder.AddToScheme,
		v1beta1kms.SchemeBuilder.AddToScheme,
		v1beta1rds.SchemeBuilder.AddToScheme,
		v1beta1resourcegroups.SchemeBuilder.AddToScheme,
		v1beta1s3.SchemeBuilder.AddToScheme,
		v1beta1s3control.SchemeBuilder.AddToScheme,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1beta1apis.SchemeBuilder.AddToScheme,
		v1beta1vpc.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
